#!/usr/bin/env bash
set -euo pipefail

cat > tools/caa/generate_assessment_cycle_from_ir.py <<'PY'
#!/usr/bin/env python3
from pathlib import Path
import json

IR = Path("examples/NMFS/pifsc_bigeye_tuna/v2/CAA_IR.json")
OUT = Path("examples/NMFS/pifsc_bigeye_tuna/v2/architecture/assessment/generated_assessment_cycle.hpp")

ir = json.loads(IR.read_text())
packages = [p["name"] for p in ir["packages"]]

include_for = {
    "LifeHistoryPackage": "../packages/life_history/life_history_package.hpp",
    "PopulationPackage": "../packages/population/population_package.hpp",
    "MovementPackage": "../packages/movement/movement_package.hpp",
    "FleetPackage": "../packages/fleet/fleet_package.hpp",
    "ObservationPackage": "../packages/observation/observation_package.hpp",
    "LikelihoodPackage": "../packages/likelihood/likelihood_package.hpp",
}

context_include_for = {
    "PopulationPackage": "../packages/population/population_context.hpp",
    "MovementPackage": "../packages/movement/movement_context.hpp",
    "FleetPackage": "../packages/fleet/fleet_context.hpp",
    "ObservationPackage": "../packages/observation/observation_context.hpp",
    "LikelihoodPackage": "../packages/likelihood/likelihood_context.hpp",
}

call_for = {
    "LifeHistoryPackage": "    LifeHistoryPackage{}(data, parameters.life, state.life);",
    "FleetPackage": "    FleetPackage{}(data, fleet_context);",
    "PopulationPackage": "    PopulationPackage{}(data, population_context);",
    "MovementPackage": "    MovementPackage{}(data, movement_context);",
    "ObservationPackage": "    ObservationPackage{}(data, observation_context);",
    "LikelihoodPackage": "    LikelihoodPackage{}(data, likelihood_context);",
}

unknown = [p for p in packages if p not in include_for]
if unknown:
    raise SystemExit(f"unknown package(s) in IR: {unknown}")

lines = [
    "#pragma once",
    "",
    "// ============================================================",
    "// AUTO-GENERATED",
    "//",
    "// Generated by:",
    "//   tools/caa/generate_assessment_cycle_from_ir.py",
    "//",
    "// Source:",
    "//   examples/NMFS/pifsc_bigeye_tuna/v2/CAA_IR.json",
    "//",
    "// DO NOT EDIT BY HAND.",
    "// ============================================================",
    "",
    '#include "../parameters/assessment_parameters.hpp"',
    '#include "../state/assessment_state.hpp"',
    '#include "../../common/model_data.hpp"',
]

for package in packages:
    lines.append(f'#include "{include_for[package]}"')
    if package in context_include_for:
        lines.append(f'#include "{context_include_for[package]}"')

lines.extend([
    "",
    "namespace bigeye_v2 {",
    "",
    "struct GeneratedAssessmentCycleFromIR {",
    "  template <typename T>",
    "  void operator()(const BigeyeModelData<T> &data,",
    "                  const AssessmentParameters<T> &parameters,",
    "                  AssessmentState<T> &state) const {",
    "    if (state.populations.size() < parameters.populations.size()) {",
    "      state.populations.resize(parameters.populations.size());",
    "    }",
    "",
    "    if (state.fleets.size() < parameters.fleets.size()) {",
    "      state.fleets.resize(parameters.fleets.size());",
    "    }",
    "",
    "    if (parameters.populations.empty() || parameters.fleets.empty()) {",
    "      return;",
    "    }",
    "",
    "    FleetContext<T> fleet_context{",
    "        &parameters.fleets[0],",
    "        &state.life,",
    "        &state.populations[0],",
    "        &state.fleets[0]};",
    "",
    "    PopulationContext<T> population_context{",
    "        &parameters.populations[0],",
    "        &state.life,",
    "        &state.fleets[0],",
    "        &state.populations[0]};",
    "",
    "    MovementContext<T> movement_context{",
    "        &parameters.movement,",
    "        &state.populations};",
    "",
    "    ObservationContext<T> observation_context{",
    "        &parameters.fleets[0],",
    "        &state.populations[0],",
    "        &state.fleets[0]};",
    "",
    "    LikelihoodContext<T> likelihood_context{",
    "        &parameters.fleets[0],",
    "        &state.fleets[0],",
    "        &state.likelihood};",
    "",
])

for package in packages:
    lines.append(call_for[package])

lines.extend([
    "  }",
    "};",
    "",
    "} // namespace bigeye_v2",
    "",
])

OUT.write_text("\n".join(lines))
print(f"wrote {OUT}")
print("generated cycle:", " -> ".join(packages))
PY

chmod +x tools/caa/generate_assessment_cycle_from_ir.py

cat > generate_bigeye_v2_caa_assessment_cycle_from_ir.sh <<'SH'
#!/usr/bin/env bash
set -euo pipefail

./generate_bigeye_v2_caa_ir.sh
python3 tools/caa/generate_assessment_cycle_from_ir.py
SH

chmod +x generate_bigeye_v2_caa_assessment_cycle_from_ir.sh

cat > run_bigeye_v2_18_ir_generated_cycle_caa_check.sh <<'SH'
#!/usr/bin/env bash
set -euo pipefail

./generate_bigeye_v2_caa_assessment_cycle_from_ir.sh

mkdir -p build/examples

cat > build/examples/bigeye_v2_18_ir_generated_cycle_caa_check.cpp <<'CPP'
#include "examples/NMFS/pifsc_bigeye_tuna/v2/architecture/assessment/generated_assessment_cycle.hpp"

#include <array>
#include <cmath>
#include <cstdlib>
#include <iostream>

namespace {
bool nearly_equal(double a, double b, double tol = 1.0e-6) {
  return std::abs(a - b) <= tol;
}
}

int main() {
  using namespace bigeye_v2;

  BigeyeModelData<double> data;
  data.n_years = 3;

  AssessmentParameters<double> parameters;
  parameters.life.log_m_young_offset = std::log(0.75);
  parameters.life.log_m_old_offset = std::log(0.65);

  parameters.populations.resize(1);
  parameters.populations[0].r0 = 1000.0;

  parameters.fleets.resize(1);
  parameters.fleets[0].sel_a50 = 5.0;
  parameters.fleets[0].sel_slope = 1.0;
  parameters.fleets[0].fbar = 0.2;
  parameters.fleets[0].q_index = 0.01;
  parameters.fleets[0].catch_sigma = 0.1;
  parameters.fleets[0].index_sigma = 0.2;

  AssessmentState<double> state;
  state.populations.resize(1);
  state.fleets.resize(1);

  state.populations[0].numbers_at_age.assign(
      static_cast<std::size_t>(data.n_years),
      std::array<double, kAges>{});

  for (int a = 0; a < kAges; ++a) {
    state.populations[0].numbers_at_age[0][a] = 1000.0;
  }

  GeneratedAssessmentCycleFromIR{}(data, parameters, state);

  if (!nearly_equal(state.life.m_at_age[0], 0.3375)) {
    std::cerr << "FAIL: generated IR cycle life history\n";
    return EXIT_FAILURE;
  }

  if (!nearly_equal(state.populations[0].numbers_at_age[1][1],
                    710.98976678322833)) {
    std::cerr << "FAIL: generated IR cycle population\n";
    return EXIT_FAILURE;
  }

  if (!nearly_equal(state.fleets[0].z_at_age[4], 0.55)) {
    std::cerr << "FAIL: generated IR cycle fleet mortality\n";
    return EXIT_FAILURE;
  }

  std::cout << "PASSED: Bigeye v2 CAA IR-generated AssessmentCycle regression\n";
  return EXIT_SUCCESS;
}
CPP

c++ -std=c++17 -O3 \
  -I. \
  build/examples/bigeye_v2_18_ir_generated_cycle_caa_check.cpp \
  -o build/examples/bigeye_v2_18_ir_generated_cycle_caa_check

./build/examples/bigeye_v2_18_ir_generated_cycle_caa_check
SH

chmod +x run_bigeye_v2_18_ir_generated_cycle_caa_check.sh

echo "created CAA IR AssessmentCycle pass and regression"
echo
echo "Run:"
echo "  ./run_bigeye_v2_18_ir_generated_cycle_caa_check.sh"
