#!/usr/bin/env bash
set -euo pipefail

cat > tools/caa/generate_execution_plan.py <<'PY'
#!/usr/bin/env python3
from pathlib import Path
import json

IR = Path("examples/NMFS/pifsc_bigeye_tuna/v2/CAA_IR.json")
OUT = Path("examples/NMFS/pifsc_bigeye_tuna/v2/CAA_EXECUTION_PLAN.json")

ir = json.loads(IR.read_text())
available = {p["name"] for p in ir["packages"]}

candidate_phases = [
    {"phase": 0, "name": "life_history", "purpose": "compute life-history state", "packages": ["LifeHistoryPackage"]},
    {"phase": 1, "name": "fleet_bootstrap", "purpose": "initialize fleet mortality before population dynamics", "packages": ["FleetPackage"]},
    {"phase": 2, "name": "population", "purpose": "advance population state", "packages": ["PopulationPackage"]},
    {"phase": 3, "name": "movement", "purpose": "move individuals across populations", "packages": ["MovementPackage"]},
    {"phase": 4, "name": "fleet", "purpose": "recompute fleet predictions after population dynamics", "packages": ["FleetPackage"]},
    {"phase": 5, "name": "observation", "purpose": "predict observations", "packages": ["ObservationPackage"]},
    {"phase": 6, "name": "likelihood", "purpose": "evaluate likelihood components", "packages": ["LikelihoodPackage"]},
]

phases = []
diagnostics = []

for phase in candidate_phases:
    missing = [pkg for pkg in phase["packages"] if pkg not in available]
    if missing:
        diagnostics.append({
            "level": "warning",
            "kind": "missing_package_for_phase",
            "phase": phase["name"],
            "missing": missing,
        })
        continue
    phases.append(phase)

plan = {
    "name": "Bigeye v2 CAA Execution Plan",
    "source": str(IR),
    "planner_version": 1,
    "phases": phases,
    "diagnostics": diagnostics,
}

OUT.write_text(json.dumps(plan, indent=2) + "\n")
print(f"wrote {OUT}")

if diagnostics:
    print("diagnostics:")
    for d in diagnostics:
        print(f"  {d['level']}: {d['kind']} {d.get('phase', '')}")
else:
    print("diagnostics: clean")
PY

chmod +x tools/caa/generate_execution_plan.py

cat > generate_bigeye_v2_caa_execution_plan.sh <<'SH'
#!/usr/bin/env bash
set -euo pipefail

./generate_bigeye_v2_caa_ir.sh
python3 tools/caa/generate_execution_plan.py
SH

chmod +x generate_bigeye_v2_caa_execution_plan.sh

cat > tools/caa/generate_assessment_cycle_from_plan.py <<'PY'
#!/usr/bin/env python3
from pathlib import Path
import json

PLAN = Path("examples/NMFS/pifsc_bigeye_tuna/v2/CAA_EXECUTION_PLAN.json")
OUT = Path("examples/NMFS/pifsc_bigeye_tuna/v2/architecture/assessment/generated_assessment_cycle.hpp")

plan = json.loads(PLAN.read_text())
phases = plan["phases"]

include_for = {
    "LifeHistoryPackage": "../packages/life_history/life_history_package.hpp",
    "PopulationPackage": "../packages/population/population_package.hpp",
    "MovementPackage": "../packages/movement/movement_package.hpp",
    "FleetPackage": "../packages/fleet/fleet_package.hpp",
    "ObservationPackage": "../packages/observation/observation_package.hpp",
    "LikelihoodPackage": "../packages/likelihood/likelihood_package.hpp",
}

context_include_for = {
    "PopulationPackage": "../packages/population/population_context.hpp",
    "MovementPackage": "../packages/movement/movement_context.hpp",
    "FleetPackage": "../packages/fleet/fleet_context.hpp",
    "ObservationPackage": "../packages/observation/observation_context.hpp",
    "LikelihoodPackage": "../packages/likelihood/likelihood_context.hpp",
}

call_for = {
    "LifeHistoryPackage": "    LifeHistoryPackage{}(data, parameters.life, state.life);",
    "FleetPackage": "    FleetPackage{}(data, fleet_context);",
    "PopulationPackage": "    PopulationPackage{}(data, population_context);",
    "MovementPackage": "    MovementPackage{}(data, movement_context);",
    "ObservationPackage": "    ObservationPackage{}(data, observation_context);",
    "LikelihoodPackage": "    LikelihoodPackage{}(data, likelihood_context);",
}

ordered_packages = []
for phase in phases:
    for package in phase["packages"]:
        ordered_packages.append(package)

unknown = [p for p in ordered_packages if p not in include_for]
if unknown:
    raise SystemExit(f"unknown package(s) in execution plan: {unknown}")

unique_packages = []
for package in ordered_packages:
    if package not in unique_packages:
        unique_packages.append(package)

lines = [
    "#pragma once",
    "",
    "// ============================================================",
    "// AUTO-GENERATED",
    "//",
    "// Generated by:",
    "//   tools/caa/generate_assessment_cycle_from_plan.py",
    "//",
    "// Source:",
    "//   examples/NMFS/pifsc_bigeye_tuna/v2/CAA_EXECUTION_PLAN.json",
    "//",
    "// DO NOT EDIT BY HAND.",
    "// ============================================================",
    "",
    '#include "../parameters/assessment_parameters.hpp"',
    '#include "../state/assessment_state.hpp"',
    '#include "../../common/model_data.hpp"',
]

for package in unique_packages:
    lines.append(f'#include "{include_for[package]}"')
    if package in context_include_for:
        lines.append(f'#include "{context_include_for[package]}"')

lines.extend([
    "",
    "namespace bigeye_v2 {",
    "",
    "struct GeneratedAssessmentCycleFromIR {",
    "  template <typename T>",
    "  void operator()(const BigeyeModelData<T> &data,",
    "                  const AssessmentParameters<T> &parameters,",
    "                  AssessmentState<T> &state) const {",
    "    if (state.populations.size() < parameters.populations.size()) {",
    "      state.populations.resize(parameters.populations.size());",
    "    }",
    "",
    "    if (state.fleets.size() < parameters.fleets.size()) {",
    "      state.fleets.resize(parameters.fleets.size());",
    "    }",
    "",
    "    if (parameters.populations.empty() || parameters.fleets.empty()) {",
    "      return;",
    "    }",
    "",
    "    FleetContext<T> fleet_context{",
    "        &parameters.fleets[0],",
    "        &state.life,",
    "        &state.populations[0],",
    "        &state.fleets[0]};",
    "",
    "    PopulationContext<T> population_context{",
    "        &parameters.populations[0],",
    "        &state.life,",
    "        &state.fleets[0],",
    "        &state.populations[0]};",
    "",
    "    MovementContext<T> movement_context{",
    "        &parameters.movement,",
    "        &state.populations};",
    "",
    "    ObservationContext<T> observation_context{",
    "        &parameters.fleets[0],",
    "        &state.populations[0],",
    "        &state.fleets[0]};",
    "",
    "    LikelihoodContext<T> likelihood_context{",
    "        &parameters.fleets[0],",
    "        &state.fleets[0],",
    "        &state.likelihood};",
    "",
])

for phase in phases:
    lines.append(f"    // Phase {phase['phase']}: {phase['name']} - {phase['purpose']}")
    for package in phase["packages"]:
        lines.append(call_for[package])
    lines.append("")

lines.extend([
    "  }",
    "};",
    "",
    "} // namespace bigeye_v2",
    "",
])

OUT.write_text("\n".join(lines))
print(f"wrote {OUT}")
print("generated phases:")
for phase in phases:
    print(f"  phase {phase['phase']}: {phase['name']} -> {', '.join(phase['packages'])}")
PY

chmod +x tools/caa/generate_assessment_cycle_from_plan.py

cat > generate_bigeye_v2_caa_assessment_cycle_from_ir.sh <<'SH'
#!/usr/bin/env bash
set -euo pipefail

./generate_bigeye_v2_caa_execution_plan.sh
python3 tools/caa/generate_assessment_cycle_from_plan.py
SH

chmod +x generate_bigeye_v2_caa_assessment_cycle_from_ir.sh

cat > inspect_bigeye_v2_caa_execution_plan.sh <<'SH'
#!/usr/bin/env bash
set -euo pipefail

python3 - <<'PY'
from pathlib import Path
import json

plan = json.loads(Path("examples/NMFS/pifsc_bigeye_tuna/v2/CAA_EXECUTION_PLAN.json").read_text())

print("CAA Execution Plan")
print()
for phase in plan["phases"]:
    packages = " -> ".join(phase["packages"])
    print(f"phase {phase['phase']}: {phase['name']}")
    print(f"  purpose: {phase['purpose']}")
    print(f"  packages: {packages}")
    print()

if plan["diagnostics"]:
    print("diagnostics:")
    for d in plan["diagnostics"]:
        print(f"  {d['level']}: {d['kind']}")
else:
    print("diagnostics: clean")
PY
SH

chmod +x inspect_bigeye_v2_caa_execution_plan.sh

echo "created CAA execution planner and plan-driven AssessmentCycle generator"
echo
echo "Run:"
echo "  ./generate_bigeye_v2_caa_execution_plan.sh"
echo "  ./inspect_bigeye_v2_caa_execution_plan.sh"
echo "  ./run_bigeye_v2_18_ir_generated_cycle_caa_check.sh"
