#!/usr/bin/env bash
set -euo pipefail

ROOT="examples/NMFS/pifsc_bigeye_tuna"
OUT="$ROOT/workflow/bigeye_data_audit_report.txt"
CSV="$ROOT/workflow/bigeye_data_audit_report.csv"

mkdir -p "$ROOT/workflow"

python3 - <<'PY'
import csv
import math
from pathlib import Path
from collections import defaultdict

root = Path("examples/NMFS/pifsc_bigeye_tuna")
out_txt = root / "workflow/bigeye_data_audit_report.txt"
out_csv = root / "workflow/bigeye_data_audit_report.csv"

candidate_files = sorted(root.glob("level*/data/synthetic_bigeye_level*_observations.csv"))

def read_rows(path):
    rows = []
    with path.open() as f:
        r = csv.DictReader(f)
        for row in r:
            fleet = row.get("fleet", "")
            ages = []
            for i in range(1, 11):
                key = f"age_{i}"
                if key not in row:
                    key = f"age{i}"
                ages.append(float(row[key]))
            rows.append({
                "path": str(path),
                "year": int(row["year"]),
                "fleet": fleet,
                "catch": float(row.get("catch_mt", row.get("catch", 0.0))),
                "index": float(row.get("index", 0.0)),
                "ages": ages,
            })
    return rows

all_rows = []
for p in candidate_files:
    try:
        all_rows.extend(read_rows(p))
    except Exception as e:
        pass

def entropy(p):
    return -sum(x * math.log(max(x, 1e-300)) for x in p)

def mean(xs):
    return sum(xs) / len(xs) if xs else float("nan")

with out_txt.open("w") as txt, out_csv.open("w", newline="") as cf:
    txt.write("Bigeye Data Audit Report\n")
    txt.write("========================\n\n")
    txt.write("Purpose\n")
    txt.write("-------\n")
    txt.write("Audit whether the synthetic observation CSVs are internally consistent\n")
    txt.write("and whether purse-seine age compositions look generated by a population\n")
    txt.write("process or by hard-coded smooth template values.\n\n")

    w = csv.writer(cf)
    w.writerow([
        "level","file","fleet","metric","age","value","note"
    ])

    txt.write("Files found\n")
    txt.write("-----------\n")
    for p in candidate_files:
        txt.write(f"{p}\n")
    txt.write("\n")

    by_level_fleet = defaultdict(list)
    for row in all_rows:
        # level directory name
        parts = Path(row["path"]).parts
        level = next((x for x in parts if x.startswith("level")), "unknown")
        by_level_fleet[(level, row["path"], row["fleet"])].append(row)

    txt.write("Fleet composition summaries\n")
    txt.write("---------------------------\n")
    for (level, path, fleet), rows in sorted(by_level_fleet.items()):
        ages_by_col = list(zip(*(r["ages"] for r in rows)))
        txt.write(f"\n{level} | {fleet} | {path}\n")
        txt.write("age,mean,min,max,range\n")
        for i, vals in enumerate(ages_by_col, start=1):
            mn, lo, hi = mean(vals), min(vals), max(vals)
            txt.write(f"{i},{mn:.12g},{lo:.12g},{hi:.12g},{hi-lo:.12g}\n")
            w.writerow([level, path, fleet, "age_mean", i, mn, "mean observed composition"])
            w.writerow([level, path, fleet, "age_range", i, hi-lo, "max-min across years"])

        age1 = [r["ages"][0] for r in rows]
        age2 = [r["ages"][1] for r in rows]
        age3 = [r["ages"][2] for r in rows]
        txt.write(f"age1_mean={mean(age1):.12g}, age2_mean={mean(age2):.12g}, age3_mean={mean(age3):.12g}\n")
        txt.write(f"entropy_mean={mean([entropy(r['ages']) for r in rows]):.12g}\n")

        # Smoothness of year-to-year changes.
        years_sorted = sorted(rows, key=lambda r: r["year"])
        if len(years_sorted) > 1:
            diffs = []
            for a, b in zip(years_sorted[:-1], years_sorted[1:]):
                diffs.append(sum(abs(x-y) for x, y in zip(a["ages"], b["ages"])))
            txt.write(f"mean_year_to_year_L1_change={mean(diffs):.12g}\n")
            w.writerow([level, path, fleet, "mean_year_to_year_L1_change", "", mean(diffs),
                        "small values imply mechanically smooth composition series"])

    # Compare Level 16 data with Level 16 fitted predicted residual file if present.
    residual = root / "level16_purse_seine_age_selectivity/outputs/bigeye_level16_age_comp_residual_diagnostics.csv"
    if residual.exists():
        txt.write("\nLevel 16 residual check\n")
        txt.write("-----------------------\n")
        rows = []
        with residual.open() as f:
            for r in csv.DictReader(f):
                if r.get("section") == "age_residual":
                    rows.append(r)
        rows.sort(key=lambda r: float(r["abs_residual"]), reverse=True)
        txt.write("Top 20 residuals\n")
        txt.write("year,fleet,age,observed,predicted,residual,abs_residual\n")
        for r in rows[:20]:
            txt.write(",".join([r["year"], r["fleet"], r["age"], r["observed"], r["predicted"], r["residual"], r["abs_residual"]]) + "\n")
            w.writerow(["level16", str(residual), r["fleet"], "top_residual", r["age"], r["abs_residual"],
                        f"year={r['year']}; observed={r['observed']}; predicted={r['predicted']}"])

    txt.write("\nInterpretation\n")
    txt.write("--------------\n")
    txt.write("If no generator source is found and the CSV age-composition values are\n")
    txt.write("smooth templates, then the model is not being fit to process-generated\n")
    txt.write("synthetic data. In that case persistent age-1 residuals should be treated\n")
    txt.write("as a data/template mismatch until a generator is recovered or rebuilt.\n")

print(f"wrote: {out_txt}")
print(f"wrote: {out_csv}")
PY

echo
echo "== Data audit preview =="
sed -n '1,180p' "$OUT"
