#!/usr/bin/env python3
from pathlib import Path
import json

IR = Path("examples/NMFS/pifsc_bigeye_tuna/v2/CAA_IR.json")
OUT = Path("examples/NMFS/pifsc_bigeye_tuna/v2/architecture/assessment/generated_assessment_cycle.hpp")

ir = json.loads(IR.read_text())
packages = [p["name"] for p in ir["packages"]]

include_for = {
    "LifeHistoryPackage": "../packages/life_history/life_history_package.hpp",
    "PopulationPackage": "../packages/population/population_package.hpp",
    "MovementPackage": "../packages/movement/movement_package.hpp",
    "FleetPackage": "../packages/fleet/fleet_package.hpp",
    "ObservationPackage": "../packages/observation/observation_package.hpp",
    "LikelihoodPackage": "../packages/likelihood/likelihood_package.hpp",
}

context_include_for = {
    "PopulationPackage": "../packages/population/population_context.hpp",
    "MovementPackage": "../packages/movement/movement_context.hpp",
    "FleetPackage": "../packages/fleet/fleet_context.hpp",
    "ObservationPackage": "../packages/observation/observation_context.hpp",
    "LikelihoodPackage": "../packages/likelihood/likelihood_context.hpp",
}

call_for = {
    "LifeHistoryPackage": "    LifeHistoryPackage{}(data, parameters.life, state.life);",
    "FleetPackage": "    FleetPackage{}(data, fleet_context);",
    "PopulationPackage": "    PopulationPackage{}(data, population_context);",
    "MovementPackage": "    MovementPackage{}(data, movement_context);",
    "ObservationPackage": "    ObservationPackage{}(data, observation_context);",
    "LikelihoodPackage": "    LikelihoodPackage{}(data, likelihood_context);",
}

unknown = [p for p in packages if p not in include_for]
if unknown:
    raise SystemExit(f"unknown package(s) in IR: {unknown}")

lines = [
    "#pragma once",
    "",
    "// ============================================================",
    "// AUTO-GENERATED",
    "//",
    "// Generated by:",
    "//   tools/caa/generate_assessment_cycle_from_ir.py",
    "//",
    "// Source:",
    "//   examples/NMFS/pifsc_bigeye_tuna/v2/CAA_IR.json",
    "//",
    "// DO NOT EDIT BY HAND.",
    "// ============================================================",
    "",
    '#include "../parameters/assessment_parameters.hpp"',
    '#include "../state/assessment_state.hpp"',
    '#include "../../common/model_data.hpp"',
]

for package in packages:
    lines.append(f'#include "{include_for[package]}"')
    if package in context_include_for:
        lines.append(f'#include "{context_include_for[package]}"')

lines.extend([
    "",
    "namespace bigeye_v2 {",
    "",
    "struct GeneratedAssessmentCycleFromIR {",
    "  template <typename T>",
    "  void operator()(const BigeyeModelData<T> &data,",
    "                  const AssessmentParameters<T> &parameters,",
    "                  AssessmentState<T> &state) const {",
    "    if (state.populations.size() < parameters.populations.size()) {",
    "      state.populations.resize(parameters.populations.size());",
    "    }",
    "",
    "    if (state.fleets.size() < parameters.fleets.size()) {",
    "      state.fleets.resize(parameters.fleets.size());",
    "    }",
    "",
    "    if (parameters.populations.empty() || parameters.fleets.empty()) {",
    "      return;",
    "    }",
    "",
    "    FleetContext<T> fleet_context{",
    "        &parameters.fleets[0],",
    "        &state.life,",
    "        &state.populations[0],",
    "        &state.fleets[0]};",
    "",
    "    PopulationContext<T> population_context{",
    "        &parameters.populations[0],",
    "        &state.life,",
    "        &state.fleets[0],",
    "        &state.populations[0]};",
    "",
    "    MovementContext<T> movement_context{",
    "        &parameters.movement,",
    "        &state.populations};",
    "",
    "    ObservationContext<T> observation_context{",
    "        &parameters.fleets[0],",
    "        &state.populations[0],",
    "        &state.fleets[0]};",
    "",
    "    LikelihoodContext<T> likelihood_context{",
    "        &parameters.fleets[0],",
    "        &state.fleets[0],",
    "        &state.likelihood};",
    "",
])

# Reference execution order for the current single-population/single-fleet
# assessment:
#   LifeHistory -> Fleet bootstrap -> Population -> Movement -> Fleet
#   -> Observation -> Likelihood
if "LifeHistoryPackage" in packages:
    lines.append(call_for["LifeHistoryPackage"])

if "FleetPackage" in packages and "PopulationPackage" in packages:
    lines.append(call_for["FleetPackage"])

for package in packages:
    if package in {"LifeHistoryPackage"}:
        continue
    lines.append(call_for[package])

lines.extend([
    "  }",
    "};",
    "",
    "} // namespace bigeye_v2",
    "",
])

OUT.write_text("\n".join(lines))
print(f"wrote {OUT}")
print("generated cycle:", " -> ".join(packages))
