#pragma once

// ============================================================
// AUTO-GENERATED
//
// Generated by:
//   tools/caa/generate_assessment_cycle_from_ir.py
//
// Source:
//   examples/NMFS/pifsc_bigeye_tuna/v2/CAA_IR.json
//
// DO NOT EDIT BY HAND.
// ============================================================

#include "../parameters/assessment_parameters.hpp"
#include "../state/assessment_state.hpp"
#include "../../common/model_data.hpp"
#include "../packages/life_history/life_history_package.hpp"
#include "../packages/population/population_package.hpp"
#include "../packages/population/population_context.hpp"
#include "../packages/movement/movement_package.hpp"
#include "../packages/movement/movement_context.hpp"
#include "../packages/fleet/fleet_package.hpp"
#include "../packages/fleet/fleet_context.hpp"
#include "../packages/observation/observation_package.hpp"
#include "../packages/observation/observation_context.hpp"
#include "../packages/likelihood/likelihood_package.hpp"
#include "../packages/likelihood/likelihood_context.hpp"

namespace bigeye_v2 {

struct GeneratedAssessmentCycleFromIR {
  template <typename T>
  void operator()(const BigeyeModelData<T> &data,
                  const AssessmentParameters<T> &parameters,
                  AssessmentState<T> &state) const {
    if (state.populations.size() < parameters.populations.size()) {
      state.populations.resize(parameters.populations.size());
    }

    if (state.fleets.size() < parameters.fleets.size()) {
      state.fleets.resize(parameters.fleets.size());
    }

    if (parameters.populations.empty() || parameters.fleets.empty()) {
      return;
    }

    FleetContext<T> fleet_context{
        &parameters.fleets[0],
        &state.life,
        &state.populations[0],
        &state.fleets[0]};

    PopulationContext<T> population_context{
        &parameters.populations[0],
        &state.life,
        &state.fleets[0],
        &state.populations[0]};

    MovementContext<T> movement_context{
        &parameters.movement,
        &state.populations};

    ObservationContext<T> observation_context{
        &parameters.fleets[0],
        &state.populations[0],
        &state.fleets[0]};

    LikelihoodContext<T> likelihood_context{
        &parameters.fleets[0],
        &state.fleets[0],
        &state.likelihood};

    LifeHistoryPackage{}(data, parameters.life, state.life);
    FleetPackage{}(data, fleet_context);
    PopulationPackage{}(data, population_context);
    MovementPackage{}(data, movement_context);
    FleetPackage{}(data, fleet_context);
    ObservationPackage{}(data, observation_context);
    LikelihoodPackage{}(data, likelihood_context);
  }
};

} // namespace bigeye_v2
